### ISSUE TITLE
auto_combine() fails in the example run

### ISSUE THREAD

**Issue by MichalOleszak** [ceweiss/GeomComb#3]
Code to produce the error:
```
library(ForecastComb)
example("auto_combine")
```

Error message:
```
Error in diag(sample_msqu_pred_error) : 
  could not find symbol "names" in environment of the generic function
```

I got the same error when trying to use different data sets.

**Comment by RoetGer** [comment]
Hi Michael,

thank you for using our package. Unfortunately, I could not reproduce the error, have you installed the new version from CRAN or directly from github? 

Could you please provide us with your sessionInfo()? Because I have found similar issues online that were related to mismatches in the R version.

Best regards.

**Comment by MichalOleszak** [comment]
Indeed, re-installing R solved the issue. Thank you!
